version: 0.1.{build}

image: Visual Studio 2019

configuration: Release

build_script:
- cmd: dotnet build -c Release src/RestApiServer/RestApiServer.csproj

test_script:
- cmd: dotnet test src/RestApiServer.UnitTests/RestApiServer.UnitTests.csproj
  
deploy:
  provider: NuGet
  api_key:
    secure: ad1GLh8FoGoaJYXJTVP2HB9xYhdNlrD7bbHUn5mdLVuU42PLpxmYqZaS+zsC3576
  skip_symbols: false
  artifact: /.*\.nupkg/
  
  on:
    branch: master
